# https://taskfile.dev

version: "3"

interval: 200ms

vars:
  NAME: "realworld"
  BIN_NAME: "{{.NAME}}_bin"
  VERSION: "v0.0.1"

tasks:
  tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/delaneyj/toolbelt/sqlc-gen-zombiezen@latest
      - go mod tidy

  sqlc:
    dir: sql
    sources:
      - "**/*.sql"
    cmds:
      - sqlc generate
      - goimports -w .

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    generates:
      - "**/*_templ.go"
    sources:
      - "**/*.templ"
    cmds:
      - templ generate .

  kill:
    cmds:
      - killall -q {{.BIN_NAME}}  || echo "Process was not running."

  hot:
    env:
      ENV: dev
    sources:
      - "**/*.go"
      - "web/static/**/*"

    deps:
      - kill
      - sqlc
      - templ
      # - inspector
      # - css

    cmds:
      - go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/main.go
      - ./{{.BIN_NAME}}

  default:
    deps:
      - hot
    silent: true
